Document: osm-imdocs
Title: Debian osm-imdocs Manual
Author: <insert document author here>
Abstract: This manual describes what osm-imdocs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/osm-imdocs/osm-imdocs.sgml.gz

Format: postscript
Files: /usr/share/doc/osm-imdocs/osm-imdocs.ps.gz

Format: text
Files: /usr/share/doc/osm-imdocs/osm-imdocs.text.gz

Format: HTML
Index: /usr/share/doc/osm-imdocs/html/index.html
Files: /usr/share/doc/osm-imdocs/html/*.html
